// Approved emails list for Stryker Christmas Store
// Add emails that are allowed to place orders

export const APPROVED_EMAILS = [
  'josh.rakosky@gmail.com',
  // Team test emails for order testing
  'team1@stryker.com',
  'team2@stryker.com',
  'team3@stryker.com',
  'team4@stryker.com',
  'team5@stryker.com',
  'team6@stryker.com',
  'team7@stryker.com',
  'team8@stryker.com',
  'team9@stryker.com',
  'team10@stryker.com',
  // Final approved emails list
  'aashish.sethi@stryker.com',
  'abdul.kasim@stryker.com',
  'abhishek.kumar78@stryker.com',
  'aditi.joshi1@stryker.com',
  'akshay.nagpal@stryker.com',
  'alma.ramirez@stryker.com',
  'alvaro.corrales@stryker.com',
  'amanda.eury@stryker.com',
  'amit.gupta4@stryker.com',
  'anal.2@stryker.com',
  'ananta.sahoo@stryker.com',
  'ananya.anand@stryker.com',
  'anil.verma@stryker.com',
  'anilverma.kottapalli@stryker.com',
  'ankit.kumar1@stryker.com',
  'ankush.nagpal@stryker.com',
  'anubhav.srivastav@stryker.com',
  'archit.sharma@stryker.com',
  'arunkumar.vc@stryker.com',
  'avinash.illindra@stryker.com',
  'bala.bonam@stryker.com',
  'benjamin.morgan@stryker.com',
  'binit.keshri@stryker.com',
  'blake.beekmann@stryker.com',
  'carlo.lalomia@stryker.com',
  'carlos.arevalo@stryker.com',
  'chandra.kumari@stryker.com',
  'chethan.at@stryker.com',
  'chuck.kourtjian@stryker.com',
  'damien.dunne@stryker.com',
  'darren.coffey@stryker.com',
  'david.excoffier@stryker.com',
  'david.pryor@stryker.com',
  'deepa.zareen@stryker.com',
  'dev.swaika@stryker.com',
  'diksha.longani@stryker.com',
  'divanshu.moza@stryker.com',
  'elizabeth.parks@stryker.com',
  'ernest.washington@stryker.com',
  'francisco.urendes@stryker.com',
  'gabriel.lobo@stryker.com',
  'ganesh.maturi@stryker.com',
  'gopal.singh@stryker.com',
  'gopichand.lingam@stryker.com',
  'harald.traub@stryker.com',
  'hareesh.malisetty@stryker.com',
  'harish.boorla1@stryker.com',
  'harshal.jagtap@stryker.com',
  'himanika.arora@stryker.com',
  'ignacio.benavides@stryker.com',
  'james.anastasio@stryker.com',
  'james.kaub@stryker.com',
  'jason.howard@stryker.com',
  'justin.moderow@stryker.com',
  'karen.landers@stryker.com',
  'karii.muror@stryker.com',
  'karunakar.kotagiri@stryker.com',
  'kimberly.morrow@stryker.com',
  'komal.angurala@stryker.com',
  'koyel.banerjee@stryker.com',
  'krishna.yemula@stryker.com',
  'lauryn.arora@stryker.com',
  'leonardo.wesley@stryker.com',
  'lisa.pfeiffer@stryker.com',
  'luke.steele@stryker.com',
  'maheshbabu.kothoju@stryker.com',
  'mandi.turner@stryker.com',
  'manjiri.ramachandran@stryker.com',
  'margaret.redmond@pomeroy.com',
  'maria.jackson@stryker.com',
  'marie.bag-ao@stryker.com',
  'mdmaksud.alam@stryker.com',
  'meghna.thite@stryker.com',
  'mike.osullivan2@stryker.com',
  'mindy.bush@stryker.com',
  'muppidi.aishwarya@stryker.com',
  'narine.markosyan@stryker.com',
  'nishant.ranjan@stryker.com',
  'nrupa.travadi@stryker.com',
  'nyasha.chidhakwa@stryker.com',
  'olaf.werner@stryker.com',
  'palak.shah@stryker.com',
  'parul.kapoor@stryker.com',
  'prabhakar.gandavarapu@stryker.com',
  'prabhu.gudneppanavar@stryker.com',
  'prashant.fauzdar@stryker.com',
  'prashanth.tummala@stryker.com',
  'prashantpara.mahalinga@stryker.com',
  'prathamesh.kondalkar@stryker.com',
  'pratik.deshmukh@stryker.com',
  'ravikiran.savirigana@stryker.com',
  'ravneet.bhardwaj@stryker.com',
  'reddy.srinivas@stryker.com',
  'ryan.delong@stryker.com',
  'sai.varun@stryker.com',
  'samuel.goff@stryker.com',
  'sanjay.kumar10@stryker.com',
  'shabana.maver@stryker.com',
  'shane.christianson@stryker.com',
  'sharon.edwards@stryker.com',
  'shaun.wernette@stryker.com',
  'sheila.mcbride@stryker.com',
  'shilpa.rani@stryker.com',
  'sharlene.fang@stryker.com',
  'shreshth.vats@stryker.com',
  'shubham.thapa@stryker.com',
  'siddharth.agarwal1@stryker.com',
  'siddhi.agrawal@stryker.com',
  'sourabh.arora@stryker.com',
  'stefania.maestri@stryker.com',
  'steve.sawicki@stryker.com',
  'sumit.khera@stryker.com',
  'surendra.shringi1@stryker.com',
  'swastik.mishra@stryker.com',
  'tanesha.coleman@stryker.com',
  'thirupathi.shada@stryker.com',
  'tony.ruocco@stryker.com',
  'umar.ashraf@stryker.com',
  'vaishali.gurjer@stryker.com',
  'veeranjaneyulu.busiraju1@stryker.com',
  'veeranjaneyulu.ravuri@stryker.com',
  'venkataramaraju.kammila@stryker.com',
  'vivek.sharma03@stryker.com',
  'waleed.akhtar@stryker.com',
  'yara.kumar@stryker.com',
  'yogithashree.rp@stryker.com',
]

// Check if an email is approved
export function isEmailApproved(email: string): boolean {
  const normalizedEmail = email.toLowerCase().trim()
  
  // If no approved emails list, allow all (for initial setup)
  if (APPROVED_EMAILS.length === 0) {
    return true
  }
  
  return APPROVED_EMAILS.includes(normalizedEmail)
}

